language: node_js

node_js:
  - '0.10'
  - '0.12'
  - iojs

notifications:
  email:
    smcarthur@mozilla.com
    jrgm@mozilla.com
  irc:
    channels:
      - 'irc.mozilla.org#fxa-bots'
    use_notice: false
    skip_join: false

env:
  - NODE_ENV=test DB=memory IMG=local
  - NODE_ENV=test DB=mysql IMG=local
  - NODE_ENV=test DB=mysql IMG=aws

before_install:
  - npm install -g npm@2
  - npm config set spin false
  - sudo apt-get install graphicsmagick
  - "mysql -e 'DROP DATABASE IF EXISTS fxa_profile;'"
  - "mysql -e 'CREATE DATABASE fxa_profile;'"

script:
  - npm run outdated
  - grunt
