language: node_js

addons:
  firefox: "39.0"

sudo: false

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

node_js:
  - '0.10'
  - '0.12'
  - '4'

script:
  - npm i
  - node_modules/.bin/ember test
