language: rust
cache: cargo
rust:
  - nightly-2018-04-28
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose
