language: node_js

node_js:
 - "0.10"
 - "0.12"
 - "4"

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

notifications:
  irc:
    channels:
      - "irc.mozilla.org#fxa-bots"
    use_notice: false
    skip_join: false

before_install:
  - if [ "$TRAVIS_NODE_VERSION" == "0.10" ]; then npm install -g npm@2; fi
  - npm config set spin false

env:
  global:
    - NODE_ENV=test
  matrix:
    - DB=memory
    - DB=mysql

install:
  # use c++-11 with node4, default compiler on downlevel versions
  - if [ $TRAVIS_NODE_VERSION == "4" ]; then CXX=g++-4.8 npm install; else npm install; fi

script:
  - grunt templates
  - if [ $DB == "mysql" ]; then ./scripts/start-travis-auth-db-mysql.sh; fi
  - npm test
  - npm outdated --depth 0
  - grunt l10n-extract
