language: node_js

node_js:
 - 0.10

services:
 - redis-server

notifications:
  email:
    - zcarter@mozilla.com
    - dcoates@mozilla.com
    - jbonacci@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#fxa"
    use_notice: false
    skip_join: false

env:
  - NODE_ENV=local KVSTORE_BACKEND=memory TOOBUSY_MAX_LAG=0
  - NODE_ENV=local KVSTORE_BACKEND=mysql REDIS_HOST=localhost TOOBUSY_MAX_LAG=0

before_script:
  - "mysql -e 'DROP DATABASE IF EXISTS test;'"
  - "mysql -e 'CREATE DATABASE test;'"
  - ./scripts/gen_keys.js

before_install:
  - sudo apt-get install libgmp3-dev
