language: node_js

node_js:
 - "0.10"

sudo: false

notifications:
  irc:
    channels:
      - "irc.mozilla.org#fxa-bots"
    use_notice: false
    skip_join: false

before_install:
  - npm config set spin false

script:
  - npm run outdated
  - grunt lint
  - grunt templates
  - npm test
