language: node_js

node_js:
 - "4"
 - "6"

dist: trusty
sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

notifications:
  irc:
    channels:
      - "irc.mozilla.org#fxa-bots"
    use_notice: false
    skip_join: false

before_install:
  - npm config set spin false

env:
  global:
    - NODE_ENV=test
    - CXX=g++-4.8
  matrix:
    - DB=memory
    - DB=mysql

script:
  - grunt templates
  - if [ $DB == "mysql" ]; then ./scripts/start-travis-auth-db-mysql.sh; fi
  - COVERALLS_REPO_TOKEN=uGetG7nOCCJ8bhZSvlXeloKqpUQDEvYDF npm test
  - npm outdated --depth 0
  - grunt l10n-extract
