language: node_js

node_js:
  - '0.10'
  - '0.12'
  - 'iojs'

sudo: false

notifications:
  email:
    smcarthur@mozilla.com
    jrgm@mozilla.com
  irc:
    channels:
      - 'irc.mozilla.org#fxa-bots'
    use_notice: false
    skip_join: false

env:
  - NODE_ENV=test DB=memory
  - NODE_ENV=test DB=mysql

before_install:
  - npm install -g npm@2
  - npm config set spin false

before_script:
  - "mysql -NBe 'select version()'"
  - "mysql -e 'DROP DATABASE IF EXISTS fxa_oauth;'"
  - "mysql -e 'CREATE DATABASE fxa_oauth;'"

script:
  - npm run outdated
  - grunt validate-shrinkwrap test

matrix:
  allow_failures:
    - node_js: "iojs"
  fast_finish: true
