language: node_js

node_js:
 - "0.10"
 - "4"

dist: trusty
sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

notifications:
  irc:
    channels:
      - "irc.mozilla.org#fxa-bots"
    use_notice: false
    skip_join: false

before_install:
  - if [ "$TRAVIS_NODE_VERSION" == "0.10" ]; then npm install -g npm@2; fi
  - npm config set spin false

env:
  global:
    - NODE_ENV=test
  matrix:
    - DB=memory
    - DB=mysql

install:
  # if node 0.120 then update npm
  - if [ "$TRAVIS_NODE_VERSION" == "0.10" ]; then npm install -g npm@2; fi
  # use c++-11 with node4, default compiler on downlevel versions
  - if [ $TRAVIS_NODE_VERSION == "4" ]; then CXX=g++-4.8 npm install; else npm install; fi

script:
  - grunt templates
  - if [ $DB == "mysql" ]; then ./scripts/start-travis-auth-db-mysql.sh; fi
  - COVERALLS_REPO_TOKEN=uGetG7nOCCJ8bhZSvlXeloKqpUQDEvYDF npm test
  - npm outdated --depth 0
  - grunt l10n-extract
