language: node_js

node_js:
 - "0.10"
 - "0.12"
 - "4"

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

notifications:
  irc:
    channels:
      - "irc.mozilla.org#fxa-bots"
    use_notice: false
    skip_join: false

before_install:
  - npm config set spin false

install:
  # use c++-11 with node4, default compiler on downlevel versions
  - if [ $TRAVIS_NODE_VERSION == "4" ]; then CXX=g++-4.8 npm install; else npm install; fi

script:
  - grunt templates
  - npm test
  - npm outdated --depth 0
  - grunt l10n-extract
