[UdpInput]
address = "127.0.0.1:4880"

[CounterFilter]
message_matcher = "Type != 'heka.counter-output'"

[debug_output]
type = "LogOutput"
message_matcher = "Type != 'heka.counter-output'"
payload_only = true

[DashboardOutput]
ticker_interval = 10
message_matcher = "Type == 'heka.counter-output'"
